const Patrimoine = require('./Patrimoine');
const Possession = require('./Possession');
const Argent = require("./Argent");
const BienMateriel = require("./BienMateriel");
const arg0 = new Argent("espèce", 20000);
const arg1 = new Argent("compte epargne", 20000);
const mat0 = new BienMateriel("ordinateur", 3000000);
const possession0 = new Possession("2023-08-18", arg0);
const possession1 = new Possession("2024-09-17", arg1);
const possession2 = new Possession("2020-08-09", mat0);
const test = new Patrimoine("rakoto");
test.addPossession(possession0);
test.addPossession(possession1);
test.addPossession(possession2);
// console.log(test.getAllActualValue());
// console.log(test.getPourcentage("espèce", "2025-08-23", 2));
// console.log(test.tauxDAmortissage("espèce", "2025-08-23", 2));
// console.log(test.getAllActualValue());
// console.log(test);
// console.log(test.getPossessions("espèce"));
